export const cryptoSymbols = [
     { title: 'X:AVAXUSD', payoutPercentage: 86, desc: 'Avalanche - United States Dollar' },
     { title: 'X:BCHEUR', payoutPercentage: 86, desc: 'Bitcoin Cash - Euro' },
     { title: 'X:BCHNUSD', payoutPercentage: 86, desc: 'Bitcoin Cash - United States Dollar' },
     { title: 'X:BCHGBP', payoutPercentage: 86, desc: 'Bitcoin Cash - Bitcoin Cash - Great Britian Pound' },
     { title: 'X:BTCJPY', payoutPercentage: 86, desc: 'Bitcoin -  Japanese yen' },
     { title: 'X:BTCEUR', payoutPercentage: 86, desc: 'Bitcoin -  Euro' },
     { title: 'X:BTCGBP', payoutPercentage: 86, desc: 'Bitcoin -  Pound sterling' },
     { title: 'X:BTCUSD', payoutPercentage: 86, desc: 'Bitcoin -  United States Dollar' },
     { title: 'X:BUSDUSD', payoutPercentage: 86, desc: 'Binance USD - United States Dollar' },
     { title: 'X:ETHBTC', payoutPercentage: 86, desc: 'Ethereum - Bitcoin' },
     { title: 'X:DOGEUSD', payoutPercentage: 86, desc: 'Dogecoin - United States Dollar' },
     { title: 'X:TONUSD', payoutPercentage: 86, desc: 'Toncoin - United States Dollar' },
     { title: 'X:LTCAUD', payoutPercentage: 86, desc: 'Litecoin - Australian Dollar' },
     { title: 'X:LTCBTC', payoutPercentage: 86, desc: 'Litecoin - Bitcoin' },
     { title: 'X:LTCEUR', payoutPercentage: 86, desc: 'Litecoin - Euro' },
     { title: 'X:LTCUSD', payoutPercentage: 86, desc: 'Litecoin - United States Dollar' },
     { title: 'X:XAUTUSD', payoutPercentage: 86, desc: 'Tether Gold - United States Dollar' },
     { title: 'X:DASHUSD', payoutPercentage: 86, desc: 'Dash - United States Dollar' },
     { title: 'X:SOLUSD', payoutPercentage: 86, desc: 'Solana - United States Dollar' },
]
export const forexSymbols = [
     { title: 'C:AEDAUD', payoutPercentage: 92, desc: 'United Arab Emirates dirham - Australian dollar' },
     { title: 'C:AEDUSD', payoutPercentage: 92, desc: 'United Arab Emirates dirham - United States Dollar' },
     { title: 'C:AEDBHD', payoutPercentage: 92, desc: 'United Arab Emirates dirham - Bahraini dinar' },
     { title: 'C:AEDCAD', payoutPercentage: 92, desc: 'United Arab Emirates dirham - Canadian dollar' },
     { title: 'C:AEDCHF', payoutPercentage: 92, desc: 'United Arab Emirates dirham - Swiss franc' },
     { title: 'C:AEDDKK', payoutPercentage: 92, desc: 'United Arab Emirates dirham - Danish krone' },
     { title: 'C:AEDEUR', payoutPercentage: 92, desc: 'United Arab Emirates dirham - Euro' },
     { title: 'C:AEDGBP', payoutPercentage: 92, desc: 'United Arab Emirates dirham - Pound sterling' },
     { title: 'C:AEDJPY', payoutPercentage: 92, desc: 'United Arab Emirates dirham - Japanese yen' },
     { title: 'C:AEDNZD', payoutPercentage: 92, desc: 'United Arab Emirates dirham - New Zealand dollar' },
     { title: 'C:AEDSAR', payoutPercentage: 92, desc: 'United Arab Emirates dirham - Saudi riyal' },
     // AUD
     { title: 'C:AUDEUR', payoutPercentage: 92, desc: 'Australian dollar - Euro' },
     { title: 'C:AUDUSD', payoutPercentage: 92, desc: 'Australian dollar - United States Dollar' },
     { title: 'C:AUDCHF', payoutPercentage: 72, desc: 'Australian dollar - Swiss franc' },
     { title: 'C:AUDJPY', payoutPercentage: 73, desc: 'Australian dollar - Japanese yen' },
     { title: 'C:AUDCAD', payoutPercentage: 90, desc: 'Australian dollar - Canadian dollar' },
     // BHD
     { title: 'C:BHDEUR', payoutPercentage: 74, desc: 'Bahraini dinar - Euro' },
     { title: 'C:BHDUSD', payoutPercentage: 74, desc: 'Bahraini dinar - United States Dollar' },
     // CAD
     { title: 'C:CADAED', payoutPercentage: 82, desc: 'Canadian dollar - United Arab Emirates dirham' },
     { title: 'C:CADCHF', payoutPercentage: 82, desc: 'Canadian dollar - Swiss franc' },
     { title: 'C:CADEUR', payoutPercentage: 82, desc: 'Canadian dollar - Euro' },
     { title: 'C:CADGBP', payoutPercentage: 82, desc: 'Canadian dollar - Pound sterling' },
     { title: 'C:CADJPY', payoutPercentage: 82, desc: 'Canadian dollar - Japanese yen' },
     { title: 'C:CADUSD', payoutPercentage: 82, desc: 'Canadian dollar - United States Dollar' },
     { title: 'C:CADAUD', payoutPercentage: 82, desc: 'Canadian dollar - Australian dollar' },
     // EUR
     { title: 'C:EURUSD', payoutPercentage: 92, desc: 'Euro - United States Dollar' },
     { title: 'C:EURAED', payoutPercentage: 89, desc: 'Euro - United Arab Emirates dirham' },
     { title: 'C:EURAUD', payoutPercentage: 89, desc: 'Euro - Australian dollar' },
     { title: 'C:EURBHD', payoutPercentage: 89, desc: 'Euro - Bahraini dinar' },
     { title: 'C:EURCAD', payoutPercentage: 89, desc: 'Euro - Canadian dollar' },
     { title: 'C:EURCHF', payoutPercentage: 89, desc: 'Euro - Swiss franc' },
     { title: 'C:EURGBP', payoutPercentage: 89, desc: 'Euro - Pound sterling' },
     { title: 'C:EURJPY', payoutPercentage: 89, desc: 'Euro - Japanese yen' },
     { title: 'C:EURKWD', payoutPercentage: 89, desc: 'Euro - Kuwaiti dinar' },
     { title: 'C:EURSGD', payoutPercentage: 89, desc: 'Euro - Singapore dollar' },
     { title: 'C:EURSAR', payoutPercentage: 89, desc: 'Euro - Saudi riyal' },
     // GBP
     { title: 'C:GBPUSD', payoutPercentage: 84, desc: 'Pound sterling - United States Dollar' },
     { title: 'C:GBPAED', payoutPercentage: 84, desc: 'Pound sterling - United Arab Emirates dirham' },
     { title: 'C:GBPAUD', payoutPercentage: 84, desc: 'Pound sterling - Australian dollar' },
     { title: 'C:GBPBHD', payoutPercentage: 84, desc: 'Pound sterling - Bahraini dinar' },
     { title: 'C:GBPCAD', payoutPercentage: 80, desc: 'Pound sterling - Canadian dollar' },
     { title: 'C:GBPCHF', payoutPercentage: 74, desc: 'Pound sterling - Swiss franc' },
     { title: 'C:GBPEUR', payoutPercentage: 84, desc: 'Pound sterling - Euro' },
     { title: 'C:GBPJPY', payoutPercentage: 78, desc: 'Pound sterling - Japanese yen' },
     { title: 'C:GBPKWD', payoutPercentage: 78, desc: 'Pound sterling - Kuwaiti dinar' },
     { title: 'C:GBPSGD', payoutPercentage: 78, desc: 'Pound sterling - Singapore dollar' },
     { title: 'C:GBPSAR', payoutPercentage: 74, desc: 'Pound sterling - Saudi riyal' },
     // USD
     { title: 'C:USDAUD', payoutPercentage: 88, desc: 'United States Dollar - Australian dollar' },
     { title: 'C:USDAED', payoutPercentage: 84, desc: 'United States dollar -  United Arab Emirates dirham' },
     { title: 'C:USDBHD', payoutPercentage: 74, desc: 'United States dollar - Bahraini dinar' },
     { title: 'C:USDCAD', payoutPercentage: 84, desc: 'United States dollar - Canadian dollar' },
     { title: 'C:USDCHF', payoutPercentage: 84, desc: 'United States dollar - Swiss franc' },
     { title: 'C:USDEUR', payoutPercentage: 92, desc: 'United States dollar - Euro' },
     { title: 'C:USDGBP', payoutPercentage: 84, desc: 'United States dollar - Pound sterling' },
     { title: 'C:USDKWD', payoutPercentage: 84, desc: 'United States dollar - Kuwaiti dinar' },
     { title: 'C:USDJPY', payoutPercentage: 84, desc: 'United States dollar - Japanese yen' },
     { title: 'C:USDSAR', payoutPercentage: 82, desc: 'United States dollar -  Saudi riyal' },
     { title: 'C:USDSGD', payoutPercentage: 83, desc: 'United States dollar -  Singapore dollar' }
]
