/** @type {import('tailwindcss').Config} */
module.exports = {
     important: true,
     content: ['./src/**/*.{js,jsx,ts,tsx}', './public/index.html'],
     theme: {
          extend: {
               backgroundImage: {
                    'logo-pattern': "url('./assets/logo-t.png')",
                    'logo-colored-pattern': "url('./assets/logo.png')",
               },
               colors: {
                    primary: 'rgb(var(--color-primary) / <alpha-value>)',
                    darkBlue: 'rgb(var(--color-darkBlue) / <alpha-value>)',
                    offWhite: 'rgb(var(--color-offWhite) / <alpha-value>)',
                    googleRed: 'rgb(var(--color-googleRed) / <alpha-value>)',

                    // your named colors
                    Orange: '#FB8122',
                    LightOrange: '#FF9B47',
                    Green: '#00743F',
                    DarkGreen: '#161a25',
                    LightBlue: '#72A2C0',
                    'ُSkyBlue': '#199FB1',
                    SoftBlue: '#A5D1E1',
                    TextGray: '#333333',
                    Gray: '#757575',
                    LightGray: '#E0E0E0',
                    OffWhite: '#F9F9F9',
                    Navy: '#161a25',
                    LightNavy: '#22293d',
                    bgWhite: 'rgb(244, 244, 246)',
                    txt: '#4a4a4a',
                    tomato: '#FF6347',
                    ethBlue: '#3C6EAF',
                    webMoneyBlue: '#006DAF',
                    tetGreen: '#26A079',
                    gold: '#FFBF00',
                    greentxt: '#77DD77',
                    peach: '#FFDAB9',
                    footerBg: '#161C2A',
                    footerTxt: 'rgb(57, 178, 255)',
                    lightGrey: 'rgb(169, 181, 203)',
                    darkStart: '#161C2A',
                    darkEnd: '#45546A',
                    fbBlue: '#3B5998',
                    darkGrey: '#2E3749',
                    silver: '#8E9199',
                    menuTxt: '#b4c2e4',
                    blueBg: '#102C52',
                    lightBlueBg: '#007CBC',
                    yellow: '#FCD535',
                    lightYellow: '#FFE97C',
                    buttonRed: '#EF4444',
                    lightButtonRed: '#F87171',
                    error: '#F44336',
                    success: '#4CAF50',
                    offBlue: '#81D4FA',
                    deepGrey: '#CCCCCC',
               },
               animation: {
                    'fade-in': 'fadeIn 0.3s ease-out forwards',
               },
               backdropBlur: { xs: '2px' },
          },

          // your custom breakpoints are fine here (this replaces defaults intentionally)
          screens: {
               sm: '480px',
               md: '680px',
               lg: '886px',
               xl: '1228px',
               '1xl': '1378px',
               '2xl': '1536px',
               '3xl': '1716px',
          },
     },
     plugins: [],
};
